# Generated by Django 4.2.3 on 2023-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature_unit',
            field=models.CharField(choices=[('C', 'Цельсий (°C)'), ('F', 'Фаренгейт (°F)'), ('K', 'Кельвин (K)')], default='C', max_length=1, verbose_name='Единица измерения'),
        ),
    ]
